remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme
title: Maria Merkulova test
description: Computer Science Graduate from University of Birmingham test
github:
  zip_url: https://github.com/InfiniteInfinities

