remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme
title: Maria Merkulova
description: Computer Science Graduate from University of Birmingham
github:
  repository_url: https://github.com/InfiniteInfinities

